In [2]:
import numpy as np

In [3]:
# create arrays

array=np.array([2,4,6,8,10])
print(array)

[ 2  4  6  8 10]


In [4]:
a=np.array([10,20,30])
b=np.array([4,6,8])

print(a+b)
print(a*b)
print(a/b)

[14 26 38]
[ 40 120 240]
[2.5        3.33333333 3.75      ]


In [5]:
# zeros and ones

print(np.zeros((5,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
data=np.array([10,20,30,40])

print("Mean:", np.mean(data))
print("Max:", np.max(data))
print("Min:", np.min(data))

Mean: 25.0
Max: 40
Min: 10
